-- 코드를 작성해주세요
WITH G1(ID, PARENT_ID, G1_ID) 
AS (
    SELECT
        D.ID, D.PARENT_ID, P.G1_ID
    FROM ECOLI_DATA D
    LEFT JOIN (SELECT ID AS G1_ID FROM ECOLI_DATA 
               WHERE PARENT_ID IS NULL) AS P 
        ON P.G1_ID = D.PARENT_ID
)
SELECT G1.ID FROM G1
    LEFT JOIN (SELECT ID FROM G1 WHERE G1_ID IS NOT NULL) AS G2
        ON G2.ID = G1.PARENT_ID
    WHERE G2.ID IS NOT NULL;
