-- 코드를 입력하세요
SELECT 
    USER_ID, PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(*) AS TOTAL FROM ONLINE_SALE
        GROUP BY USER_ID, PRODUCT_ID) AS DUPLICATE
WHERE TOTAL > 1
    ORDER BY USER_ID ASC, PRODUCT_ID DESC;
