-- 코드를 입력하세요
SELECT * FROM
    (SELECT
        DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
        PRODUCT_ID,
        USER_ID,
        SALES_AMOUNT
    FROM ONLINE_SALE
        UNION
    SELECT
        DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
        PRODUCT_ID,
        IF(PRODUCT_ID > 0, NULL, PRODUCT_ID) AS USER_ID,
        SALES_AMOUNT
    FROM OFFLINE_SALE) AS SALES
WHERE MONTH(SALES_DATE) = 3
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
