-- 코드를 작성해주세요
SELECT 
    I.ITEM_ID,
    I.ITEM_NAME,
    I.RARITY
FROM ITEM_INFO I
    JOIN ITEM_TREE T 
        ON T.ITEM_ID = I.ITEM_ID
    LEFT JOIN (SELECT ITEM_ID, RARITY FROM ITEM_INFO) AS P 
        ON P.ITEM_ID = T.PARENT_ITEM_ID
WHERE P.RARITY = 'RARE'
    ORDER BY I.ITEM_ID DESC;